export async function seed(knex) {
  await knex('products').del();

  const categories = await knex('categories').select('id', 'slug');
  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  await knex('products').insert([
    // Rice
    {
      name: 'Jammu Basmati Rice',
      slug: 'jammu-basmati-rice',
      description: 'Long-grain, intensely aromatic basmati aged 12 months. Each grain stands apart, releasing a fragrance that fills the kitchen — the hallmark of true Himalayan rice.',
      price: 299.00,
      original_price: 349.00,
      image_url: 'https://images.unsplash.com/photo-1586201375362-ce7e78b5de09?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      badge: 'Bestseller',
      featured: true,
      sort_order: 1,
    },
    {
      name: 'Biryani King Special',
      slug: 'biryani-king-special',
      description: 'Master blend of aged Himalayan basmati crafted specifically for biryani — long, separate grains that absorb spices beautifully.',
      price: 329.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      badge: "Chef's Pick",
      featured: true,
      sort_order: 2,
    },
    {
      name: 'Zaika Aroma Rice',
      slug: 'zaika-aroma-rice',
      description: 'Everyday premium rice with a natural buttery aroma. Ideal for pulao, khichdi, and simple steamed rice.',
      price: 199.00,
      original_price: 229.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '2 kg',
      sort_order: 3,
    },
    // Dry Fruits
    {
      name: 'Kashmir Almonds',
      slug: 'kashmir-almonds',
      description: 'Wild-harvested, naturally sun-dried Himalayan almonds with a rich, buttery flavour. Hand-selected for premium quality.',
      price: 699.00,
      original_price: 849.00,
      image_url: 'https://images.unsplash.com/photo-1508222720893-62a0e5a9fb69?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '500 g',
      badge: 'Premium',
      featured: true,
      sort_order: 4,
    },
    {
      name: 'Himalayan Cashews',
      slug: 'himalayan-cashews',
      description: 'Whole, creamy cashews with a naturally sweet flavour. Sourced from the finest orchards and gently dried.',
      price: 549.00,
      original_price: 649.00,
      image_url: 'https://images.unsplash.com/photo-1562771154-e8a7c62e2f8a?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '500 g',
      sort_order: 5,
    },
    {
      name: 'Premium Pistachios',
      slug: 'premium-pistachios',
      description: 'Roasted and lightly salted Himalayan pistachios, hand-selected for size and flavour.',
      price: 849.00,
      image_url: 'https://images.unsplash.com/photo-1590080874088-eec64895b423?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '500 g',
      sort_order: 6,
    },
    {
      name: 'Dried Apricots',
      slug: 'dried-apricots',
      description: 'Sun-dried Himalayan apricots with a natural tart sweetness — no added sugar, no preservatives.',
      price: 399.00,
      image_url: 'https://images.unsplash.com/photo-1598511757339-8b58f3a3e82b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '300 g',
      badge: 'New',
      sort_order: 7,
    },
    // Spices
    {
      name: 'Green Cardamom',
      slug: 'green-cardamom',
      description: 'Hand-picked from Himalayan spice gardens, intensely aromatic green cardamom pods. The queen of spices from Kashmir.',
      price: 449.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '200 g',
      badge: 'New',
      featured: true,
      sort_order: 8,
    },
    {
      name: 'Whole Black Pepper',
      slug: 'whole-black-pepper',
      description: 'Sun-dried whole peppercorns with an intense, complex heat. Freshly grind for maximum aroma.',
      price: 249.00,
      image_url: 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '250 g',
      sort_order: 9,
    },
    {
      name: 'Ceylon Cinnamon Sticks',
      slug: 'ceylon-cinnamon-sticks',
      description: 'True Ceylon cinnamon sticks sourced from the finest spice traders — soft, delicate, and unlike cassia.',
      price: 299.00,
      image_url: 'https://images.unsplash.com/photo-1526313462543-09e6acdfbd81?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '150 g',
      sort_order: 10,
    },
    // Heritage Pulses
    {
      name: 'Bhaderwahi Rajmash',
      slug: 'bhaderwahi-rajmash',
      description: 'GI-tagged kidney beans from the Bhaderwah valley — earthy, hearty, and incomparably flavourful. A true Himalayan heritage ingredient.',
      price: 389.00,
      image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['pulses'],
      weight: '1 kg',
      badge: 'Heritage',
      featured: true,
      sort_order: 11,
    },
    // Traditional
    {
      name: 'Kashmiri Noon Chai',
      slug: 'kashmiri-noon-chai',
      description: 'Pink salt tea with rose petals and traditional Kashmiri spices. The original salted pink chai — warming, creamy, and soul-nourishing.',
      price: 349.00,
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '100 g',
      badge: 'Heritage',
      featured: true,
      sort_order: 12,
    },
    {
      name: 'Himalayan Chia Seeds',
      slug: 'himalayan-chia-seeds',
      description: 'Nutrient-dense chia seeds — rich in omega-3, fibre, and protein. Perfect for smoothies, puddings, and overnight oats.',
      price: 299.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '250 g',
      sort_order: 13,
    },
  ]);
}
