export async function seed(knex) {
  await knex('products').del();

  const categories = await knex('categories').select('id', 'slug');
  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  await knex('products').insert([
    // ── RICE ──────────────────────────────────────────────────────────────────
    {
      name: 'Neekz Jammu Basmati Rice',
      slug: 'neekz-jammu-basmati-rice',
      description: 'Also known as Pakistani Basmati, this is a premium variety of Basmati rice typically associated with the Jammu region in India, specifically known for its high-quality aromatic rice. Available in 30Kg & 10Kg Packing.',
      price: 299.00,
      original_price: 349.00,
      image_url: 'https://delivery.pixelbin.io/predictions/outputs/1d/sr/upscaleRestricted/019e34a6-0f96-7ff5-96e2-e840edbc7cab/result_0.jpeg',
      category_id: catMap['rice'],
      weight: '1 kg',
      badge: 'Bestseller',
      featured: true,
      sort_order: 1,
    },
    {
      name: 'Neekz XXXL Basmati Rice',
      slug: 'neekz-xxxl-basmati-rice',
      description: 'XXXL Basmati Rice refers to extra-long grain basmati rice, known for its long, slender grains that elongate further when cooked. This variety is prized for its fluffy, non-sticky texture and fragrant aroma, making it a preferred choice for dishes like biryani, pulao, or any meal where basmati rice is used. Available in 30Kg & 10Kg Packing.',
      price: 329.00,
      original_price: 379.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      badge: 'Premium',
      featured: true,
      sort_order: 2,
    },
    {
      name: 'Neekz Aroma Basmati Rice',
      slug: 'neekz-aroma-basmati-rice',
      description: 'A premium variety of Basmati rice typically associated with the Jammu region in India, specifically known for its high-quality aromatic rice. Available in 30Kg & 10Kg Packing.',
      price: 279.00,
      original_price: 319.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 3,
    },
    {
      name: 'Neekz Classic Basmati Rice (IInd Wand)',
      slug: 'neekz-classic-basmati-rice',
      description: '"Neekz Classic Basmati Rice" refers to a type or brand of Basmati rice sold in larger quantities. Basmati rice is a long-grain variety known for its fragrance and fluffy texture when cooked. Available in 30Kg & 10Kg Packing.',
      price: 249.00,
      original_price: 289.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 4,
    },
    {
      name: 'Neekz Zaika Basmati Rice (Tibar)',
      slug: 'neekz-zaika-basmati-rice',
      description: 'Neekz Zaika Basmati rice refers to a grade of Basmati rice that is slightly smaller but still retains much of the quality, flavour, and aroma of regular long-grain Basmati rice. Available in 30Kg & 10Kg Packing.',
      price: 229.00,
      original_price: 269.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 5,
    },
    {
      name: 'Neekz Exotic Basmati Rice (Dobar)',
      slug: 'neekz-exotic-basmati-rice',
      description: 'Dobar Basmati rice refers to a grade of Basmati rice where the grains are broken more than the higher grades like Tibar or premium full-grain rice. In Dobar rice, around 25–40% of the grains may be broken, but the characteristic fragrance, flavor, and cooking qualities of Basmati rice remain. It is more affordable due to the broken grains but still widely used in daily cooking. Available in 30Kg & 10Kg Packing.',
      price: 189.00,
      original_price: 219.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 6,
    },
    {
      name: 'Neekz Saffron Basmati Rice (Mini Dobar)',
      slug: 'neekz-saffron-basmati-rice',
      description: 'Mini Dobar is typically the most economical grade of Basmati and is often used for bulk cooking or everyday meals where the appearance of the grains is not as important. It\'s still a great option for dishes that prioritize flavor and fragrance, like khichdi, fried rice, or simple boiled rice served with stews or curries. Available in 30Kg & 10Kg Packing.',
      price: 169.00,
      original_price: 199.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 7,
    },
    {
      name: 'Neekz Apricot Basmati Rice (Super Mongra)',
      slug: 'neekz-apricot-basmati-rice',
      description: 'Apricot Basmati Rice typically refers to medium grain basmati rice, known for its taste, slender grains that elongate further when cooked. This variety is prized for its fluffy, non-sticky texture and fragrant aroma. Available in 30Kg & 10Kg Packing.',
      price: 219.00,
      original_price: 249.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 8,
    },
    {
      name: 'Neekz Sajda Basmati Rice (Mongra)',
      slug: 'neekz-sajda-basmati-rice',
      description: 'Mongra rice is a type of fragrant rice popular in parts of India. It is similar to Basmati rice but typically shorter in grain length. Mongra rice has a strong aroma and a distinct flavor, making it popular in certain regions for traditional dishes, especially in central and northern India. Available in 30Kg & 10Kg Packing.',
      price: 199.00,
      original_price: 229.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 9,
    },
    {
      name: 'Neekz Blueberry Sharbati Rice',
      slug: 'neekz-blueberry-sharbati-rice',
      description: 'Sharbati rice is a premium variety of rice, known for its long grain, aromatic fragrance, and soft texture. Available in 30Kg Packing.',
      price: 259.00,
      original_price: 299.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 10,
    },
    {
      name: 'Neekz Red Cherry Ratna Rice',
      slug: 'neekz-red-cherry-ratna-rice',
      description: 'Ratna rice is a high-yielding, medium-grain variety of rice developed in India. Available in 30Kg Packing.',
      price: 149.00,
      original_price: 179.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 11,
    },
    {
      name: 'Neekz Little Mogra Rice',
      slug: 'neekz-little-mogra-rice',
      description: 'Mongra rice is often favored in local cuisines for everyday meals due to its affordability and decent nutritional content. Available in 30Kg Packing.',
      price: 139.00,
      original_price: 169.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 12,
    },
    {
      name: 'Neekz Green Apple China Rice',
      slug: 'neekz-green-apple-china-rice',
      description: 'China rice is commonly used in traditional rice-based dishes. It is often served with rich gravies and aromatic curries. Available in 30Kg Packing.',
      price: 129.00,
      original_price: 159.00,
      image_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      sort_order: 13,
    },
    {
      name: 'Neekz Biryani King Special',
      slug: 'neekz-biryani-king-special',
      description: 'Special biryani rice typically refers to high-quality, long-grain rice used specifically for making biryani, a popular and aromatic dish across South Asia and the Middle East. The rice varieties most commonly used for biryani. Available in 30Kg Packing.',
      price: 319.00,
      original_price: 369.00,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['rice'],
      weight: '1 kg',
      badge: "Chef's Pick",
      featured: true,
      sort_order: 14,
    },

    // ── DRY FRUITS ────────────────────────────────────────────────────────────
    {
      name: 'Neekz Raisins',
      slug: 'neekz-raisins',
      description: 'Raisins are a type of dried grape that are sweet and chewy, and are often used in baking and cooking. Available in 250gm Packing.',
      price: 179.00,
      original_price: 219.00,
      image_url: 'https://images.unsplash.com/photo-1542010589005-d1eacc3918f2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '250 g',
      sort_order: 15,
    },
    {
      name: 'Neekz Almonds',
      slug: 'neekz-almonds',
      description: 'Almonds are nuts that are high in fat and a good source of protein, fiber, and vitamins and minerals. Available in 250gm Packing.',
      price: 349.00,
      original_price: 399.00,
      image_url: 'https://images.unsplash.com/photo-1542010589005-d1eacc3918f2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '250 g',
      badge: 'Premium',
      featured: true,
      sort_order: 16,
    },
    {
      name: 'Neekz Cashews',
      slug: 'neekz-cashews',
      description: 'Cashews are kidney-shaped nuts that grow from the cashew apple, a fleshy stalk that\'s technically a swollen fruit stem. Available in 250gm Packing.',
      price: 399.00,
      original_price: 449.00,
      image_url: 'https://images.unsplash.com/photo-1590080874088-eec64895b423?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '250 g',
      sort_order: 17,
    },
    {
      name: 'Neekz Pistachios',
      slug: 'neekz-pistachios',
      description: 'Pistachios are the seeds of the pistachio tree, Pistacia vera, and are technically a type of drupe, a fleshy tree fruit that contains a seed with a shell. Available in 250gm Packing.',
      price: 499.00,
      original_price: 579.00,
      image_url: 'https://images.unsplash.com/photo-1590080874088-eec64895b423?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['dry-fruits'],
      weight: '250 g',
      sort_order: 18,
    },

    // ── WELLNESS / HEALTH ─────────────────────────────────────────────────────
    {
      name: 'Neekz Breakfast Mix',
      slug: 'neekz-breakfast-mix',
      description: 'Breakfast Mix contains almonds, cashews, raisins, black raisins, pumpkin seeds, sunflower seeds & flax seeds. A nutritious and wholesome blend to start your day. Available in 200gm Packing.',
      price: 299.00,
      original_price: 349.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      badge: 'New',
      sort_order: 19,
    },
    {
      name: 'Neekz Chia Seeds',
      slug: 'neekz-chia-seeds',
      description: 'Chia seeds are high in fiber and omega-3 fatty acids, and they have many health benefits. A superfood perfect for smoothies, puddings, and overnight oats. Available in 200gm Packing.',
      price: 249.00,
      original_price: 299.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 20,
    },
    {
      name: 'Neekz Dried Apricots',
      slug: 'neekz-dried-apricots',
      description: 'Rich in vitamin A, beta-carotene, and other carotenoids, apricots are excellent for promoting eye health. 100% Natural, no added sugar, no preservatives. Available in 200gm Packing.',
      price: 279.00,
      original_price: 329.00,
      image_url: 'https://images.unsplash.com/photo-1598511757339-8b58f3a3e82b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 21,
    },
    {
      name: 'Neekz Panchmeva',
      slug: 'neekz-panchmeva',
      description: 'Neekz Panchmeva contains almonds, cashews, dates, black raisin, green raisin — a traditional mixed dry fruit blend. Available in 200gm Packing.',
      price: 349.00,
      original_price: 399.00,
      image_url: 'https://images.unsplash.com/photo-1542010589005-d1eacc3918f2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 22,
    },
    {
      name: 'Neekz Dried Figs',
      slug: 'neekz-dried-figs',
      description: 'Fresh figs are rich in nutrients while being relatively low in calories, making them a great addition to a healthy diet. Available in 200gm Packing.',
      price: 269.00,
      original_price: 319.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 23,
    },
    {
      name: 'Neekz Black Raisins',
      slug: 'neekz-black-raisins',
      description: 'Neekz Black Raisins help prevent bone disorders like osteoporosis and improve bone density, reducing the risk of fractures and bone-related injuries, especially in older adults. Available in 200gm Packing.',
      price: 199.00,
      original_price: 239.00,
      image_url: 'https://images.unsplash.com/photo-1542010589005-d1eacc3918f2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 24,
    },
    {
      name: 'Neekz Dried Strawberry',
      slug: 'neekz-dried-strawberry',
      description: 'Dried strawberries are a healthy and delicious snack that offers many health benefits, such as vitamin C, antioxidants, fiber and low calorie content. Available in 200gm Packing.',
      price: 289.00,
      original_price: 339.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 25,
    },
    {
      name: 'Neekz Dried Kiwi',
      slug: 'neekz-dried-kiwi',
      description: 'Dried Kiwi helps boost the immune system. Kiwis are powerful sources of antioxidants that boost immunity and help prevent respiratory ailments like asthma. It also promotes digestive health and helps improve your vision. Available in 200gm Packing.',
      price: 289.00,
      original_price: 339.00,
      image_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '200 g',
      sort_order: 26,
    },

    // ── WHOLE SPICES ──────────────────────────────────────────────────────────
    {
      name: 'Neekz Green Cardamom',
      slug: 'neekz-green-cardamom',
      description: 'Green cardamom is a highly prized spice used in cooking and traditional medicine, known for its intense, aromatic flavor with hints of citrus and mint. Available in 50gm & 100gm Packing.',
      price: 199.00,
      original_price: 249.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      badge: 'Premium',
      featured: true,
      sort_order: 27,
    },
    {
      name: 'Neekz Black Pepper',
      slug: 'neekz-black-pepper',
      description: 'Black pepper, often called the "king of spices," offers numerous health benefits due to its active compound piperine: Improves Digestion, Boosts Nutrient Absorption, Antioxidant Properties, Anti-Inflammatory Effect. Available in 50gm & 100gm Packing.',
      price: 149.00,
      original_price: 179.00,
      image_url: 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 28,
    },
    {
      name: 'Neekz Cinnamon Rolls',
      slug: 'neekz-cinnamon-rolls',
      description: 'Benefits of Neekz Cinnamon Rolls: It has antioxidant properties, it\'s anti-inflammatory, anti-bacterial and anti-fungal, it may have anti-viral properties, and it may help lower blood sugar and reduce the risk of type-2 diabetes. Available in 50gm & 100gm Packing.',
      price: 129.00,
      original_price: 159.00,
      image_url: 'https://images.unsplash.com/photo-1526313462543-09e6acdfbd81?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 29,
    },
    {
      name: 'Neekz Cloves',
      slug: 'neekz-cloves',
      description: 'Benefits of Neekz Cloves: Contain important nutrients, high in antioxidants, may improve liver health, may help protect against cancer, and may help regulate blood sugar. Available in 50gm & 100gm Packing.',
      price: 159.00,
      original_price: 199.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 30,
    },
    {
      name: 'Neekz Black Cardamom',
      slug: 'neekz-black-cardamom',
      description: 'Benefits of Neekz Black Cardamom: Contains antibacterial and antiseptic properties, good for liver health, promotes heart health, and good for digestion. Available in 50gm & 100gm Packing.',
      price: 179.00,
      original_price: 219.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 31,
    },
    {
      name: 'Neekz Cumin Seeds',
      slug: 'neekz-cumin-seeds',
      description: 'Benefits of Neekz Cumin Seeds: May help treat diarrhea, helps control blood sugar, fights bacteria and parasites, and has an anti-inflammatory effect. Available in 50gm & 100gm Packing.',
      price: 99.00,
      original_price: 129.00,
      image_url: 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 32,
    },
    {
      name: 'Neekz Fennel Seeds',
      slug: 'neekz-fennel-seeds',
      description: 'Benefits of Neekz Fennel Seeds: Contains protective plant compounds, may maintain a healthy heart, may support healthy skin, and may be anti-inflammatory. Available in 50gm & 100gm Packing.',
      price: 99.00,
      original_price: 129.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 33,
    },
    {
      name: 'Neekz Bay Leaves',
      slug: 'neekz-bay-leaves',
      description: 'Benefits of Neekz Bay Leaves: Good for diabetes management, improves digestion, treats respiratory conditions, and fights against fungal infections. Available in 50gm & 100gm Packing.',
      price: 89.00,
      original_price: 109.00,
      image_url: 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 34,
    },
    {
      name: 'Neekz Carom Seeds (Ajwain)',
      slug: 'neekz-carom-seeds-ajwain',
      description: 'Benefits of Neekz Carom Seeds (Ajwain): Helps in weight loss, aids in digestion, treats common cold and cough, and eases joint pain. Available in 50gm & 100gm Packing.',
      price: 89.00,
      original_price: 109.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 35,
    },
    {
      name: 'Neekz Sabut Masale',
      slug: 'neekz-sabut-masale',
      description: 'Benefits of Neekz Sabut Masale: Helps with digestion, provides strong antioxidants, regulates blood pressure & improves heart health, and reduces inflammation. Available in 50gm & 100gm Packing.',
      price: 199.00,
      original_price: 249.00,
      image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['spices'],
      weight: '100 g',
      sort_order: 36,
    },

    // ── HERITAGE PULSES ───────────────────────────────────────────────────────
    {
      name: 'Neekz Bhaderwahi Rajmash',
      slug: 'neekz-bhaderwahi-rajmash',
      description: 'Bhaderwahi Rajmash is a special variety of kidney beans (rajma) from the Bhaderwah region in J&K. Known for its small size and unique taste, Bhaderwahi rajmash has a distinct flavor compared to the regular rajma varieties found in other parts of India. It\'s highly valued for its creamy texture and rich taste when cooked. Available in 1kg Packing.',
      price: 389.00,
      original_price: 449.00,
      image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['pulses'],
      weight: '1 kg',
      badge: 'Heritage',
      featured: true,
      sort_order: 37,
    },

    // ── NOON CHAI (Kashmir Special Tea) ──────────────────────────────────────
    {
      name: 'Neekz Noon Chai',
      slug: 'neekz-noon-chai',
      description: 'Pink Kashmiri tea, also known as Noon Chai or Sheer Chai, is a traditional beverage from Kashmir, India. It\'s distinct for its unique pink color and slightly salty taste, unlike the typical sweetened teas. Available in 250gm & 1Kg Packing.',
      price: 449.00,
      original_price: 549.00,
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '250 g',
      badge: 'Heritage',
      featured: true,
      sort_order: 38,
    },
    {
      name: 'Neekz Noon Chai (Lacha)',
      slug: 'neekz-noon-chai-lacha',
      description: 'Neekz Kashmir Special Noon Chai Lacha variety — a traditional Pink Kashmiri tea with a distinctive texture and rich, authentic Kashmiri flavor. Available in 1Kg Packing.',
      price: 799.00,
      original_price: 949.00,
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '1 kg',
      sort_order: 39,
    },
    {
      name: 'Neekz Noon Chai (Zero Fine)',
      slug: 'neekz-noon-chai-zero-fine',
      description: 'Neekz Kashmir Special Noon Chai Zero Fine — a specially processed variant of the traditional Kashmiri pink salt tea, offering a smooth, refined taste. Available in 1Kg Packing.',
      price: 849.00,
      original_price: 999.00,
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '1 kg',
      sort_order: 40,
    },
    {
      name: 'Neekz Noon Chai (Super Fine)',
      slug: 'neekz-noon-chai-super-fine',
      description: 'Neekz Kashmir Special Noon Chai Super Fine — the finest grade of traditional Kashmiri pink salt tea, with an exceptionally smooth blend and authentic salty-creamy flavor. Available in 1Kg Packing.',
      price: 899.00,
      original_price: 1049.00,
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['health'],
      weight: '1 kg',
      badge: 'Premium',
      sort_order: 41,
    },
  ]);
}
